-- 코드를 작성해주세요
WITH MINUS AS(
SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR_DATE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR_DATE AS YEAR, ABS(MAX_SIZE-SIZE_OF_COLONY) AS YEAR_DEV, E.ID FROM ECOLI_DATA as E JOIN MINUS as M ON YEAR_DATE=YEAR(E.DIFFERENTIATION_DATE) ORDER BY YEAR_DATE, YEAR_DEV